### ISSUE TITLE
Why is Pty abstract?  I would like to access the underlying Fd.

### ISSUE THREAD

**Issue by tomjaguarpaw** [merijn/posix-pty#8]
Is there a good reason `Pty` is abstract?  I would like to access the underlying `Fd` to, for example, run `select` on it.

**Comment by merijn** [comment]
To be honest, it's mostly because I wrote this for some other program I was working on. But I've been distracted from working on both for months, so haven't had time to get this into better shape. I plan to revisit this and hopefully turn it into a more useful package Soon (TM)

**Comment by merijn** [comment]
Which select would you want to use it with? Since I'm cleaning up things anyway I could take that into account. The alternative would be to provide blocking IO/STM actions to wait on input?

**Comment by tomjaguarpaw** [comment]
I think I expected to be able to use it with this package, but in the end I never got round to trying it.

http://hackage.haskell.org/package/select-0.4.0.1/docs/System-Posix-IO-Select.html

Basically I wanted to be able to block on multiple `Fd`s at once, but I don't really mind how that's achieved.

Additionally I found @proger's fork https://github.com/proger/posix-pty allowed me to build on Linux.  I would suggest merging that.  It helped a lot!

**Comment by proger** [comment]
Beware of the fork, there's some bug in linux terminal handling which results a child process getting killed  with SIGHUP which I haven't properly investigated.

**Comment by merijn** [comment]
@tomjaguarpaw that select package would generally be a bad idea, because select() doesn't scale that well with large numbers of `Fd`'s, additionally you'd be fighting the thread management done by the GHC runtime. It would be better to use the `threadWaitRead` and `threadWaitWrite` primitives in GHC.Conc.IO, or their STM versions if you want to poll, as these hook directly into GHC's thread management. I'm adding a way to work with those.

@proger Right now I'm working on making the C code work cross-platform on FreeBSD and OSX, I'll look into how I can fit the linux code into that afterwards. I don't think I will merge the pull request as-is, since I'm against hardcoding constants like that, but the the API should end up closer to what your fork currently has.

**Comment by tomjaguarpaw** [comment]
@merijn I will bow to your superior knowledge of concurrent Haskell.  All I really wanted was a way to poll multiple things at once.

**Comment by merijn** [comment]
The new version exports IO and STM primitives for blocking.
